# Generated by Django 5.2.6 on 2025-10-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0003_stationentitiesmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='junctionboxmaster',
            fields=[
                ('junctionid', models.AutoField(primary_key=True, serialize=False)),
                ('junctionname', models.CharField(max_length=255)),
                ('junctiondesc', models.TextField(blank=True, null=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('stationentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctionboxmaster', to='Location.stationentitiesmaster')),
            ],
        ),
    ]
