# Generated by Django 5.2.6 on 2025-10-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logicalassetmaster',
            fields=[
                ('logicalassetid', models.AutoField(primary_key=True, serialize=False)),
                ('logicalassetname', models.TextField(blank=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
