# Generated by Django 5.2.6 on 2025-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0002_logicalassetmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severitymaster',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('severitystring', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unitofmeasurementmaster',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('unitmeasurename', models.TextField(blank=True)),
                ('abbrivation', models.TextField(blank=True, null=True)),
                ('zeroafterdecimal', models.IntegerField()),
                ('sensortype', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
