# Generated by Django 5.2.6 on 2025-11-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('users', '0006_usermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCreation',
            fields=[
                ('schedule', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('completeDate', models.DateField()),
                ('scheduleDate', models.DateField()),
                ('isBlockrequired', models.IntegerField()),
                ('blockStartStamp', models.IntegerField()),
                ('blockEndStamp', models.IntegerField()),
                ('auto_dataTable_rid', models.IntegerField()),
                ('auto_assestAttributeLink_id', models.IntegerField()),
                ('auto_boundaryValue', models.IntegerField()),
                ('auto_failureValue', models.IntegerField()),
                ('auto_smsmsg', models.CharField(max_length=500)),
                ('auto_edgeStamp', models.IntegerField()),
                ('auto_cardStamp', models.IntegerField()),
                ('auto_smsStamp', models.IntegerField()),
                ('auto_assignStamp', models.IntegerField()),
                ('app_feedback', models.TextField(blank=True, null=True)),
                ('app_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('app_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenancetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_types', to='maintenance.typemaster')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_status', to='maintenance.statusmaster')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to='maintenance.taskmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_users', to='users.usermaster')),
            ],
        ),
    ]
