# Generated by Django 5.2.6 on 2025-11-05 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0004_operatormaster_alarmcreation'),
        ('junction', '0003_severitymaster_unitofmeasurementmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('statusText', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('maintenancetypename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('taskmaster', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=200)),
                ('frequency_days', models.IntegerField()),
                ('schedulelimitdate', models.DateField()),
                ('isBlockrequired', models.IntegerField()),
                ('physicalasset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_inventory', to='asset.assetinventory')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severitymaster', to='junction.severitymaster')),
            ],
        ),
    ]
