# Generated by Django 5.2.6 on 2025-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='machinename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
