# Generated by Django 5.2.6 on 2025-11-25 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_taskmaster_machinename'),
        ('users', '0007_alter_usermaster_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('taskassignmentid', models.AutoField(primary_key=True, serialize=False)),
                ('task_number', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usermaster')),
                ('taskmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='maintenance.taskmaster')),
            ],
            options={
                'ordering': ['scheduled_date', 'task_number'],
                'unique_together': {('taskmaster', 'task_number')},
            },
        ),
    ]
