# Generated by Django 5.2.6 on 2025-11-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_taskmaster_created_at_taskmaster_updated_at_and_more'),
        ('users', '0007_alter_usermaster_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usermaster'),
        ),
    ]
