# Generated by Django 5.2.6 on 2025-11-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_taskmaster_user'),
        ('users', '0007_alter_usermaster_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermaster'),
        ),
    ]
