# Generated by Django 5.2.6 on 2025-12-04 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_taskmaster_user'),
        ('users', '0007_alter_usermaster_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('startdate', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskCloser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('machinename', models.CharField(blank=True, max_length=255, null=True)),
                ('isBlockrequired', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.taskmaster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assignment_id', models.IntegerField(help_text='Reference to the task assignment ID')),
                ('task_number', models.IntegerField(help_text='Task number for identification')),
                ('taskmaster', models.IntegerField(help_text='Task master ID')),
                ('taskname', models.CharField(help_text='Name of the task', max_length=255)),
                ('asset_id', models.IntegerField(blank=True, help_text='Asset ID reference', null=True)),
                ('assigned_user_id', models.IntegerField(blank=True, help_text='ID of user who completed the task', null=True)),
                ('scheduled_date', models.DateField(help_text='Original scheduled date')),
                ('completed_date', models.DateField(default=django.utils.timezone.now, help_text='Date when task was completed')),
                ('maintenance_start_time', models.TimeField(help_text='Maintenance start time in 24-hour format')),
                ('maintenance_stop_time', models.TimeField(help_text='Maintenance stop time in 24-hour format')),
                ('start_time_display', models.CharField(help_text='Start time display format (e.g., 09:30 AM)', max_length=20)),
                ('stop_time_display', models.CharField(help_text='Stop time display format (e.g., 05:45 PM)', max_length=20)),
                ('duration', models.CharField(help_text='Duration of maintenance (e.g., 8h 15m)', max_length=20)),
                ('is_successful', models.BooleanField(default=True, help_text='Whether the task was completed successfully')),
                ('feedback', models.TextField(help_text='Maintenance feedback and notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
            ],
            options={
                'verbose_name': 'Task Completion',
                'verbose_name_plural': 'Task Completions',
                'db_table': 'task_completions',
                'ordering': ['-completed_date', 'task_number'],
                'indexes': [models.Index(fields=['taskmaster'], name='task_comple_taskmas_f92430_idx'), models.Index(fields=['completed_date'], name='task_comple_complet_df1d6d_idx'), models.Index(fields=['assigned_user_id'], name='task_comple_assigne_2380d1_idx'), models.Index(fields=['task_assignment_id'], name='task_comple_task_as_e7c26b_idx'), models.Index(fields=['is_successful'], name='task_comple_is_succ_fe58d2_idx')],
            },
        ),
    ]
