# Generated by Django 5.2.6 on 2025-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancefeedback_taskcloser_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='assigned_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
