# Generated by Django 5.2.6 on 2025-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('assetid', models.AutoField(primary_key=True, serialize=False)),
                ('assetname', models.CharField(max_length=200)),
                ('asssetprefix', models.CharField(max_length=200)),
                ('assetstatus', models.CharField(max_length=300)),
            ],
        ),
    ]
