# Generated by Django 5.2.6 on 2025-10-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('junction', '0003_severitymaster_unitofmeasurementmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('assetinventoryid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturermodel', models.CharField(max_length=200)),
                ('manufactureddate', models.DateField()),
                ('manufactureyear', models.IntegerField()),
                ('serialnumber', models.CharField(max_length=200)),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('railwaycode', models.CharField(max_length=200)),
                ('isRDPMSasset', models.CharField(max_length=200)),
                ('assetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetmaster', to='asset.assetmaster')),
                ('junctionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctionboxmaster', to='junction.junctionboxmaster')),
            ],
        ),
    ]
