# Generated by Django 5.2.6 on 2025-11-01 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetinventory'),
        ('junction', '0003_severitymaster_unitofmeasurementmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAttributeMaster',
            fields=[
                ('assetattributemasterid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetattributemaster', to='asset.assetmaster')),
                ('unitofmeasurementmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitofmeasurementmaster', to='junction.unitofmeasurementmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AssestAttributelink',
            fields=[
                ('assetattributelink', models.AutoField(primary_key=True, serialize=False)),
                ('sensorserial', models.TextField()),
                ('sensorvalue', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('portnumber', models.CharField(max_length=200)),
                ('testpoint', models.CharField(max_length=200)),
                ('testpointlocation', models.CharField(max_length=200)),
                ('pulsevalue', models.FloatField()),
                ('lolimit', models.IntegerField()),
                ('hilimit', models.IntegerField()),
                ('chnagethreshold_percentage', models.FloatField()),
                ('datacollectionfrequency_minutes', models.IntegerField()),
                ('wireferrrules', models.CharField(max_length=200)),
                ('activewindowhours', models.CharField(max_length=200)),
                ('isdashboardattribute', models.IntegerField()),
                ('colorcondition', models.CharField(max_length=200)),
                ('assetinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetinventory', to='asset.assetinventory')),
                ('assetattributemaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetattributemaster', to='asset.assetattributemaster')),
            ],
        ),
    ]
