# Generated by Django 5.2.6 on 2025-11-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assetattributemaster_assestattributelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorMaster',
            fields=[
                ('mathoperator', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.TextField()),
                ('mathexpression', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmCreation',
            fields=[
                ('alarmsetup', models.AutoField(primary_key=True, serialize=False)),
                ('thresholdvalue', models.FloatField()),
                ('message', models.TextField()),
                ('actiontext', models.TextField()),
                ('alerttolevel', models.IntegerField()),
                ('repeat', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('assetattributelink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_links', to='asset.assestattributelink')),
                ('mathoperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatormaster', to='asset.operatormaster')),
            ],
        ),
    ]
