# Generated by Django 5.2.6 on 2025-09-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMaster',
            fields=[
                ('zoneid', models.AutoField(primary_key=True, serialize=False)),
                ('zonename', models.CharField(max_length=100)),
                ('zonedesc', models.TextField(blank=True, null=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('divisionid', models.AutoField(primary_key=True, serialize=False)),
                ('divisionname', models.CharField(max_length=255)),
                ('divisiondesc', models.TextField(blank=True, null=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='Location.zonemaster')),
            ],
        ),
    ]
