# Generated by Django 5.2.6 on 2025-10-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMaster',
            fields=[
                ('stationid', models.AutoField(primary_key=True, serialize=False)),
                ('stationname', models.CharField(max_length=200)),
                ('stationdesc', models.TextField(blank=True, null=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='Location.divisionmaster')),
            ],
        ),
    ]
