# Generated by Django 5.2.6 on 2025-10-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_stationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationEntitiesMaster',
            fields=[
                ('entityid', models.AutoField(primary_key=True, serialize=False)),
                ('entityname', models.CharField(max_length=200)),
                ('entitydesc', models.TextField(blank=True, null=True)),
                ('prefixcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='Location.stationmaster')),
            ],
        ),
    ]
