# Generated by Django 5.2.6 on 2025-10-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleMaster',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=200)),
                ('roledesc', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('roletype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrolemaster', to='users.usertypemaster')),
            ],
        ),
    ]
