# Generated by Django 5.2.6 on 2025-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrolemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProtectedEntityMaster',
            fields=[
                ('peid', models.AutoField(primary_key=True, serialize=False)),
                ('pename', models.CharField(max_length=200)),
            ],
        ),
    ]
