# Generated by Django 5.2.6 on 2025-10-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprotectedentitymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermissionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canCreate', models.BooleanField(default=True)),
                ('canRead', models.BooleanField(default=True)),
                ('canUpdate', models.BooleanField(default=True)),
                ('canDelete', models.BooleanField(default=True)),
                ('canViewReport', models.BooleanField(default=True)),
                ('canPrintReport', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('protectedentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userperticted_master', to='users.userprotectedentitymaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrolepermissionmap', to='users.userrolemaster')),
            ],
        ),
    ]
