# Generated by Django 5.2.6 on 2025-10-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrolepermissionmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelMaster',
            fields=[
                ('levelid', models.AutoField(primary_key=True, serialize=False)),
                ('levelname', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
