# Generated by Django 5.2.6 on 2025-10-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_stationentitiesmaster'),
        ('users', '0005_userlevelmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('userphone', models.IntegerField()),
                ('usermail', models.EmailField(max_length=254)),
                ('userdesignation', models.CharField(max_length=200)),
                ('alertrecipient', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sendsms', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisionmaster', to='Location.divisionmaster')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationmaster', to='Location.stationmaster')),
                ('userlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlevelmaster', to='users.userlevelmaster')),
                ('userrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrolemaster', to='users.userrolemaster')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermaster', to='users.usertypemaster')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonemaster', to='Location.zonemaster')),
            ],
        ),
    ]
