# Generated by Django 5.2.6 on 2025-11-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='userphone',
            field=models.CharField(max_length=20),
        ),
    ]
